=== BourbonWarfare/potato_backend/static/xml/squad.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT squad (name, email, web?, picture?, title?, member+)>
<!ATTLIST squad nick CDATA #REQUIRED>

<!ELEMENT member (name, email, remark?)>
<!ATTLIST member id CDATA #REQUIRED nick CDATA #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT picture (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT remark (#PCDATA)>

=== BourbonWarfare/potato_backend/static/xml/squad.xml
<?xml version="1.0"?>
<!DOCTYPE squad SYSTEM "/static/xml/squad.dtd">
<?xml-stylesheet href="/static/xml/squad.xsl?" type="text/xsl"?>
<squad nick="BW">
    <name>Bourbon Warfare</name>
    <email>team@bourbonwarfare.com</email>
    <web>http://www.BourbonWarfare.com</web>
    <picture>/static/img/BWLogov2.paa</picture>
    <title>Bourbon Warfare</title>{% for remark in remarks %}
    <member id="{{remark.steam_id}}" nick="{{remark.profile_name}}">
        <name>{{remark.nickname if remark.nickname else ''}}</name>
        <email></email>
        <remark>{{remark.remark if remark.remark else ''}}</remark>
    </member>{% endfor %}
</squad>
